
<div class="row">

    <div class="col-3 menu">
        <h4>Liste des Candidat</h4>

        <label>Anja</label>
        <div class="form-group">
            <img src="../images/user.png" width="190px">

        </div>
        <hr>
        <label>Rino</label>
        <div class="form-group">
            <img src="../images/user.png" width="190px">
        </div>
        <label>Josoa</label>
        <div class="form-group">
            <img src="../images/user.png" width="200px">
        </div>
        <hr>
        <label>Mamitina</label>
        <div class="form-group">
            <img src="../images/user.png" width="200px">
        </div>
        <label>Vonjy</label>
        <div class="form-group">
            <img src="../images/user.png" width="200px">
        </div>

    </div>
    <br>
    <div class="col-6">
        <p>Video</p>
        <video id="video_background" preload="auto" autoplay="true" loop="loop" muted="muted" volume="0" style="width: 400px">
            <source src="../images/jork.mp4">
        </video>
        <p>Video 1</p>
        <video id="video_background" preload="auto" autoplay="false" loop="loop" muted="muted" volume="0" style="width: 400px">
            <source src="../images/jork.mp4">
        </video>
        <p>Video 2</p>
        <video id="video_background" preload="auto" autoplay="false" loop="loop" muted="muted" volume="0" style="width: 400px">
            <source src="../images/jork.mp4">
        </video>
    </div>

    <div class="col-3 right">
        <div class="aside">
            <h2>Commms</h2>
            <p>Chania is a city on the island of Crete.</p>
            <h2>Where?</h2>
            <p>Crete is a Greek island in the Mediterranean Sea.</p>
            <h2>How?</h2>
            <p>You can reach Chania airport from all over Europe.</p>
        </div>
    </div>

</div>


<style>

    * {
        box-sizing: border-box;
    }

    .row::after {
        content: "";
        clear: both;
        display: block;

    }
    [class*="col-"] {
        float: left;
        padding: 15px;
    }

    /* For desktop: */
    .col-1 {width: 8.33%;}
    .col-2 {width: 16.66%;}
    .col-3 {width: 25%;}
    .col-4 {width: 33.33%;}
    .col-5 {width: 41.66%;}
    .col-6 {width: 50%;}
    .col-7 {width: 58.33%;}
    .col-8 {width: 66.66%;}
    .col-9 {width: 75%;}
    .col-10 {width: 83.33%;}
    .col-11 {width: 91.66%;}
    .col-12 {width: 100%;}

    @media only screen and (max-width: 768px) {
        /* For mobile phones: */
        [class*="col-"] {
            width: 100%;
        }
    }
</style>