
<div class="row">
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block" onclick="playVid()" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#myModal">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block" data-toggle="modal" data-target="#myModal">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-md-3">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><img class="img-thumbnail" src="../public/images/user.png" style="margin-top: -11px !important;" ></span>

            <div class="info-box-content">
                <span class="info-box-text">
                    ANARANA : RALIJAONA Vonjy <br>
                    LAHARANA : 3
                </span>
              <span class="info-box-number"><button class="btn btn-success btn-flat btn-block">Jerena</button></span>
            </div>                   <!-- /.info-box-content -->
        </div>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="pauseVid()"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Mombamomba</h4>
      </div>
      <div class="modal-body">
            <div class="embed-responsive embed-responsive-4by3">
              <video id="video_background" preload="auto" autoplay="false" loop="loop"  >
                  <source id="myVideo" src="../public/images/jork.mp4">
              </video>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <img class="img-thumbnail" src="../public/images/user.png" style="height: 250px; width:250px; " >
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Anarana</label>
                        <input type="text" class=" form-control disabled" disabled="true" >
                    </div>
                    <div class="form-group">
                        <label>Daty nahaterahana</label>
                        <input type="text" class=" form-control disabled" disabled="true" >
                    </div>
                    <div class="form-group">
                        <label>Vondrona politika</label>
                        <input type="text" class=" form-control disabled" disabled="true" >
                    </div>
                </div>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="pauseVid()">Akatona</button>
      </div>
    </div>
  </div>
</div>


<style>

    * {
        box-sizing: border-box;
    }

    .row::after {
        content: "";
        clear: both;
        display: block;

    }
    [class*="col-"] {
        float: left;
        padding: 15px;
    }

    /* For desktop: */
    .col-1 {width: 8.33%;}
    .col-2 {width: 16.66%;}
    .col-3 {width: 25%;}
    .col-4 {width: 33.33%;}
    .col-5 {width: 41.66%;}
    .col-6 {width: 50%;}
    .col-7 {width: 58.33%;}
    .col-8 {width: 66.66%;}
    .col-9 {width: 75%;}
    .col-10 {width: 83.33%;}
    .col-11 {width: 91.66%;}
    .col-12 {width: 100%;}

    @media only screen and (max-width: 768px) {
        /* For mobile phones: */
        [class*="col-"] {
            width: 100%;
        }
    }
</style>
<script type="text/javascript">
    var vid = document.getElementById("video_background"); 
    pauseVid();
    function playVid() { 
        vid.play(); 
    } 

    function pauseVid() { 
        vid.pause(); 
    }
</script>