<!-- <?php //echo $this->layout()->content; ?> -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Observatoire</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="../public/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="../public/dist/css/AdminLTE.min.css">
  <link rel="stylesheet" href="../public/dist/css/skins/_all-skins.min.css">
  <link rel="stylesheet" href="../public/bootstrap/css/datatable.min.css">
  <link rel="stylesheet" href="../public/plugins/jqueryui/jquery-ui.css">
  <link rel="stylesheet" href="../public/plugins/datepicker/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="../public/plugins/ammap/ammap.css">
  <script src="../public/plugins/jQuery/jQuery-2.2.0.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="../public/plugins/jqueryui/jquery-ui.js"></script>
  <script src="../public/bootstrap/js/chart.min.js"></script>
  <script src="../public/plugins/datepicker/bootstrap-datetimepicker.min.js"></script>
  <script src="../public/plugins/datepicker/bootstrap-datetimepicker.min.js"></script>
  <script src="../public/plugins/ammap/ammap.js"></script>
  <script src="../public/plugins/ammap/maps/js/madagascarHigh.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="icon" type="image/png" href="../../public/images/logompmp.png" />
  <style type="text/css">
        .notification{
            z-index: 10;
        }        
  </style>
</head>
<body class="skin-green layout-boxed fixed sidebar-mini"  >
<div class="wrapper">
  <header class="main-header">
    <a href="#" class="logo">
      <span class="logo-lg"><b>FIDNET</b></span>
    </a>
    <nav class="navbar navbar-static-top">
        <a href="#" class="sidebar-toggle glyphicon glyphicon-list" data-toggle="offcanvas" ></a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <span class="hidden-xs">Mr/Mme </span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
  </header>
  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu">
        <li class="header">MENU</li>
        <li class="active treeview">
          <a href="">
            <i class="fa fa-list-alt"></i> <span>ACUUEIL</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>LOI</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>BUREAU DE VOTE</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>TELECHARGEMENT</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>FLOWCHART</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>FAQ</span>
          </a>
          <a href="">
            <i class="fa fa-list-alt"></i> <span>ELECTEUR</span>
          </a>
        </li>
    </section>
  </aside>
<div class="content-wrapper">
<section class="content">
  <?php echo $this->layout()->content; ?>
</section>
</div>
  <footer class="main-footer">
    <strong>footer .
  </footer>
</div>



<script src="../public/plugins/jQuery/jQuery-2.2.0.min.js"></script>
<script src="../public/bootstrap/js/bootstrap.min.js"></script>
<script src="../public/dist/js/app.min.js"></script>
<script src="../public/dist/js/demo.js"></script>
<script src="../public/bootstrap/js/datatable.min.js"></script>

<script type="text/javascript">

  

</script>

</body>

</html>
